version: '3.9'
services:
  thesis_db:
    container_name: thesis_db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thesis
    ports:
      - '3306:3306'
