version: '3.9'
services:
  thesis_db:
    container_name: thesis_db
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thesis
    ports:
      - '3306:3306'
  thesis_redis:
    image: redis
    platform: linux/x86_64
    container_name: thesis_redis
    command: redis-server --requirepass secret
    environment:
      - REDIS_PORT=6379
    ports:
      - '6379:6379'
